### ISSUE TITLE
UI should be more self-explainatory

### ISSUE THREAD

**Issue by ToX82** [Vikasg7/Live-Quotes-Portfolio#1]
While I love this little tool, I've had some troubles installing it. 

I think that you should explain better that you need to use google finance to get the stock's symbol.

Secondly, the "delete" icon on my pc is not visible, it's just a dot. And it should ask for confirmation, to be sure I'm not deleting something wrong.

Finally, it would be great if clicking on a symbol could bring you to its google finance's page. That would be super useful :)

**Comment by Vikasg7** [comment]
Thanks for the input. Will definitely make changes when get time. PR are always welcome though.

**Comment by ToX82** [comment]
I did a PR containing all(most) my requests. Hope this can be useful. Also, I think that an icon like this could be more pertinent:

https://cdn2.iconfinder.com/data/icons/bussiness-1/20/60-512.png

But it's only a suggestion, I'm fine with the current icon too :+1:

**Comment by Vikasg7** [comment]
I updated the extension on chrome webstore. Hopefully, it will work just as you desired. I also updated the ICON though.
