### ISSUE TITLE
Stock list disappeared

### ISSUE THREAD

**Issue by ToX82** [Vikasg7/Live-Quotes-Portfolio#3]
The stocks listing is empty since a few days. Could this be related do some update in chrome 61?

I'm still investigating to see if I can find the problem though...

**Comment by ToX82** [comment]
It was not chrome's fault, after all :)

Looks like google has stopped providing the json-based stock quotes. At least, this url format `https://www.google.com/finance/info?client=ob&infotype=infoonebox&hl=en&q=*************`has been discontinued.

With a bit of reverse engineering I have found out that new data are coming from this URL:  `https://www.google.com/finance/getprices?q=RACE&x=BIT&i=120&p=10m&f=d,c,v,o,h,l&df=cpct&auto=1`

It's still a bit unclear to me how to read those data, though...

**Comment by ToX82** [comment]
Could this be a valid alternative for downloading stock's values? https://www.alphavantage.co/

**Comment by ToX82** [comment]
Good news, there is a new new endpoint here, with (it seems) all of the needed data.
`https://finance.google.com/finance?output=json&q=BIT:RACE`

The bad news is that same url, if used with multiple stocks, gives a different result without the stocks values.

**Comment by Vikasg7** [comment]
Yes, Google discontinued or changed the API. 
`https://finance.google.com/finance?output=json&q=BIT:RACE` is coming back with too much data. Do you know how to get only quotes. Also, how did you find this? May be, I can dig in more.

**Comment by ToX82** [comment]
I have found something on StackOverflow, there is a good summary here: https://stackoverflow.com/questions/46070126/google-finance-json-stock-quote-stopped-working

Unfortunately, nothing that really solves the problem. Also, the new API (my 2nd post here) seems to be returning strange quotes...

**Comment by Vikasg7** [comment]
`https://finance.google.com/finance?output=json&q=BIT:RACE`
is a JSON representation of this page
https://finance.google.com/finance?q=BIT:RACE

As the latter page has more info than just price info, JSON representation also showing that extra info.

Now, coming to using this API in our extension, my concern is google captchas. I guess, when we use this API to ping individual tickers regularly after an interval say 10 seconds, Google might throw captchas as it does with the google search for example. But again, I am not sure about this.

The second alternative is to use Yahoo API, which is 10-20 Minutes late (It was 10 minutes late in my test).
www.financialwisdomforum.org/gummy-stuff/Yahoo-data.htm

I think we should give google API a try and see whether it blocks or not. By blocking I mean throw captchas.

What do you suggest?

**Comment by ToX82** [comment]
I'd try with the google data first, real time data is a big deal I think...

**Comment by ToX82** [comment]
Did you happen to make some tests with the last google url?

I am testing it indeed, since this morning (it's 4pm here), and it seems to be working correctly. No captchas, at least.

**Comment by Vikasg7** [comment]
No, I am not able to. Crowed with work these days. may be in weekends.
how did you test it?
did you amend chrome extension?

**Comment by ToX82** [comment]
Not really, I've made a simple jquery webpage retreiving those data every 30 seconds.

Bad news though: after a few (a lot) more tests, google started refusing my requests and when opening a google webpage it asked me for a captcha...

**Comment by Vikasg7** [comment]
I told you. Google is fu*kin captcha shooting machine.

**Comment by Vikasg7** [comment]
So we are left with yahoo.

**Comment by ToX82** [comment]
Yahoo has some query limit (pretty high though: https://developer.yahoo.com/yql/guide/usage_info_limits.html). And is shows delayed data, so I'd personally prefere to try with something else first. 

Did you check this?
https://www.alphavantage.co/

It's free and real time, but I'm having some troubles finding some small cap stocks... I don't know if they just don't cover those or what.

**Comment by ToX82** [comment]
Meanwhile, I'm trying alphavantage.
The stock symbols can be obtained through yahoo finance as they use the same format (ie. RACE.MI or ADE.F).

You need a (free) api key to fetch all of the data, and the api itself is pretty straightforward, even though I don't personally like how the json data is formatted. One big advantage is that everything is real time, and every number has 4 decimal precision.

It seems to be somewhat reliable, but sometimes it gets really slow. In my test each request takes between 500ms to 20 seconds. Most of them are on the fastest side though.

Their advice is to avoid more than ~100 calls per minute.

**Comment by Vikasg7** [comment]
That advice is with one api key. When I will be using one API key in our chrome extension and as there are many users of this chrome extension, this limit is bound to break.
However, this is the only real time alternative left with us now. agree?

**Comment by ToX82** [comment]
Yeah, I think so, that's the only real time possibility imo.
Regarding the API key, maybe a viable option would be to ask the users to generate one when they install (or update) the extension? To be honest, their website states that they don't limit the request in any way... but forcing every user to have a personal api key is probably the best situation anyway.

Also, they don't provide stock symbols lookup (I've asked to their awesome customer care). While this is not a functionality in the chrome extension, I am personally writing something to add that functionality (you can see that my fork, it's raw and dirty but it's just test for now). I think this would be a useful addition, but switching to alphavantage would break this..

**Comment by Vikasg7** [comment]
I have to completely rewrite this chrome extension as the current one is badly written. I will use one api key initially and will wait for alphavantage to excuse.  I will be using Angular2 this time.

**Comment by Vikasg7** [comment]
Ok, @ToX82,
First of all, sorry, it has taken a more than a month. First I am able to write it from scratch with Angular. I was stuck with angular2 as it wasn't behaving as I thought. But I managed to have a workaround. So you can download the whole repo as a zip file or git clone the repo and then do 'load unpacked extensions' in chrome. Please test it for some time and let me know if any bugs (not the additions).

Regards,

**Comment by Vikasg7** [comment]
@ToX82 Let me know if you are available to test it out. Otherwise, I will just post it on the webstore. Thanks

**Comment by ToX82** [comment]
Hello @Vikasg7. I am already testing it indeed. It works, but it's a little bit raw compared to the previous version. Most importatly, it doesn't show the day's variations, but only the ROI (saying NaN if you don't specify quantity and cost. The old extension had those informations and I think it was nice (I always track more stocks than what I actually have in my portfolio).

Also, in the previous version I liked the possibility to add a stock without the need to go in the settings page. It was more user friendly, IMO.

**Comment by Vikasg7** [comment]
1. Yeah, Previously it had Change and %Change. I totally forgot about them.
2. Sorry, this time we have to keep the add stock to the settings because of the structure of the application. Previously, the code was badly setup but the app was more professional but this time its opposite. Lol.

I am going to see how can I bring back those Change and % Change. Hope It will be easy.

**Comment by Vikasg7** [comment]
Ok @ToX82,
You should try the newest version/commit. Now it looks more clean and less raw. I have added change and %change, though I have to manually calculate them with previous day close. AAPL don't match but MSFT does match. So have a look at it. I also took care of the NaN problem this time. Hopefully, you will like it this time.

**Comment by ToX82** [comment]
This is much better! This could be a good 2.0 release :+1:

**Comment by Vikasg7** [comment]
I pushed it to the chrome webstore. Update it and enjoy!

**Comment by Vikasg7** [comment]
Hello @ToX82,
The Change and %Change numbers are wrong if not all but most of the cases. As I didn't had a direct source of it, I had to manually calculate them. Do you thing we should take them out?

**Comment by ToX82** [comment]
I did the manual calculation too in my tests, and the results seems to be correct. I'll do some testing tomorrow though. 
What I really can't stand is that even alphavantage is not real time...

**Comment by Vikasg7** [comment]
"What I really can't stand is that even alphavantage is not real time... "
Some exchanges come with delays and I too think that alphavantage is slow and restrictive if pinged more. One of the extension users emailed me same.
"Regarding change and % change"
Actually, the previous day's close is not same as the previous close on the current day. 
The above line might be confusing but it is true. 
Also, I think I have a google alternative if you could test is it out that would be great. 
https://finance.google.com/finance/getprices?q=MSFT&x=NASD&p=1d&f=c
the above URL gives you the current price.

**Comment by Vikasg7** [comment]
I pushed an update to correct the change and %change 2 days ago. It is fine now
